# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Test application on PR

on:
  pull_request:
    branches: [ master ]
  merge_group:
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-test-application:
    name: Build and Test application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - name: Build and push Docker image
        uses: docker/build-push-action@15560696de535e4014efeff63c48f16952e52dd1
        with:
          context: .
          push: false
          tags: ${{ github.event.repository.name }}:master
          cache-from: type=gha
          cache-to: type=gha,mode=max
